### ISSUE TITLE
Add support of CodeCov

### ISSUE THREAD

**Issue by aleksieiev** [Java-Arctic-Ratel/repair-service#4]
As a developer I want to know that my code is well designed and meet code quality requirements.
For this purposes we need to have CodeCov service which should attach reports for each pull request (PR).
See: https://codecov.io/gh

**Comment by sergeyarhutik** [comment]
I need to get approval from you to add CodeCov to Java-Arctic-Ratel

**Comment by aleksieiev** [comment]
Approved
